CAR_PREDICT_URL = "http://0.0.0.0:8080/predict"

all_makes = {
   "Alfa":[
      "Romeo"
   ],
   "Audi":[
      "Q5",
      "A3",
      "Q3",
      "A4",
      "Q7",
      "A5",
      "A6",
      "Q8",
      "Q2",
      "Tt",
      "E-tron",
      "A1",
      "S4"
   ],
   "Baic":[
      "Kenbo"
   ],
   "Bmw":[
      "Serie",
      "X1",
      "X5",
      "M340i",
      "I3",
      "335",
      "X3",
      "X4",
      "120i",
      "Cabrio",
      "420i",
      "128ti",
      "225xe",
      "M240i",
      "340i",
      "Ix3",
      "2181i",
      "X2",
      "325i",
      "Bmw",
      "116",
      "M2"
   ],
   "Byd":[
      "Song",
      "Idolphin",
      "Yuan",
      "Qin"
   ],
   "Changan":[
      "Cs",
      "Cargo"
   ],
   "Chery":[
      "Qq",
      "Yoya",
      "Tiggo",
      "Qq3"
   ],
   "Chevrolet":[
      "Optra",
      "Silverado",
      "D-max",
      "N300",
      "Tracker",
      "Super",
      "Onix",
      "Sail",
      "Sonic",
      "Samurai",
      "Equinox",
      "Captiva",
      "Aveo",
      "Luv",
      "Spark",
      "Rodeo",
      "Chevrolet",
      "Cruze",
      "Grand",
      "Traverse",
      "Joy",
      "Epica",
      "Beat",
      "Vivant",
      "Colorado",
      "Van",
      "Blazer",
      "Nhr",
      "Swift",
      "Trooper",
      "Tahoe",
      "Zafira",
      "Hhr",
      "Trailblazer",
      "Wagon",
      "Camaro",
      "Cheyenne",
      "Corsa",
      "Vitara",
      "N400",
      "Sprint"
   ],
   "Citroën":[
      "C4",
      "C-elysée",
      "C3",
      "Berlingo",
      "C5",
      "Ds3"
   ],
   "Cupra":[
      "Formentor"
   ],
   "Daewoo":[
      "Cielo",
      "Nubira",
      "Damas"
   ],
   "Dahiatsu":[
      "Delta"
   ],
   "Daihatsu":[
      "Grand",
      "Terios",
      "Sirion"
   ],
   "Dfm/dfsk":[
      "Eq6410lf",
      "Eq6390pf22qx",
      "Van",
      "Glory"
   ],
   "Dodge":[
      "Journey",
      "Ram",
      "Coronet",
      "Durango"
   ],
   "Ds":[
      "Ds3",
      "Ds4",
      "Ds7"
   ],
   "Fiat":[
      "Strada",
      "Uno",
      "Fiorino",
      "500",
      "Mobi",
      "Pulse",
      "Cronos",
      "Palio"
   ],
   "Ford":[
      "F-150",
      "Bronco",
      "Fusion",
      "Ranger",
      "Escape",
      "Fiesta",
      "Explorer",
      "Edge",
      "Ecosport",
      "Sport",
      "Focus",
      "Mustang",
      "Raptor",
      "Nueva"
   ],
   "Foton":[
      "Cargo"
   ],
   "Great":[
      "Wall"
   ],
   "Honda":[
      "Cr-v",
      "Pilot",
      "Hr-v",
      "Accord",
      "Fit",
      "Odyssey",
      "Wr-v",
      "Civic"
   ],
   "Hummer":[
      "H3"
   ],
   "Hyundai":[
      "Santa",
      "Tucson",
      "Accent",
      "Creta",
      "Elantra",
      "Starex",
      "Graviti",
      "New",
      "Getz",
      "H100",
      "Grand",
      "Veracruz",
      "I35",
      "Atos",
      "Hb20x",
      "Santamo",
      "Kona",
      "I20",
      "Hb20s",
      "Sonata",
      "Ioniq",
      "I30",
      "Hb20"
   ],
   "Isuzu":[
      "Amigo"
   ],
   "Jac":[
      "E10x",
      "S2",
      "B-cross"
   ],
   "Jaguar":[
      "F-pace",
      "E-pace"
   ],
   "Jeep":[
      "Renegade",
      "Grand",
      "Wrangler",
      "Compass",
      "Cherokee",
      "Gladiator"
   ],
   "Jetour":[
      "X70"
   ],
   "Jmc":[
      "Landwind"
   ],
   "Kia":[
      "New",
      "Sportage",
      "Soul",
      "Cerato",
      "Picanto",
      "Sorento",
      "Rio",
      "Niro",
      "Carens",
      "Stonic",
      "Carnival",
      "Seltos",
      "K",
      "Grand",
      "Soluto"
   ],
   "Land":[
      "Rover"
   ],
   "Lexus":[
      "Gx",
      "Lx"
   ],
   "Mahindra":[
      "Kuv100"
   ],
   "Mazda":[
      "3",
      "Cx-30",
      "Cx-5",
      "2",
      "B2200",
      "Mpv",
      "Cx-50",
      "Cx-3",
      "Cx-9",
      "Bt-50",
      "B2600",
      "6",
      "626",
      "Allegro",
      "Cx-7",
      "Mx-5",
      "Cx-90",
      "323"
   ],
   "Mercedes-benz":[
      "Clase",
      "Vito",
      "Glc",
      "E",
      "C",
      "Ml",
      "Mb",
      "Amg",
      "350",
      "250",
      "B",
      "Gle",
      "Glc250",
      "Gla",
      "C250",
      "Cla",
      "Glk300",
      "A"
   ],
   "Mg":[
      "Zs",
      "3",
      "Gt",
      "Marvel"
   ],
   "Mini":[
      "Cooper",
      "John",
      "Countryman",
      "Morris",
      "Countryman\\xa0hibrid"
   ],
   "Mitsubishi":[
      "Montero",
      "Nativa",
      "Outlander",
      "Lancer",
      "L200",
      "Asx",
      "Eclipse"
   ],
   "Nissan":[
      "Sentra",
      "Frontier",
      "March",
      "X-trail",
      "Np300",
      "Note",
      "D22",
      "Kicks",
      "Xtrail",
      "Versa",
      "Qashqai",
      "Altima",
      "Tiida",
      "Murano",
      "Pathfinder",
      "Patrol",
      "Navara",
      "D22/np300",
      "Ad",
      "Urvan"
   ],
   "Opel":[
      "Crossland"
   ],
   "Peugeot":[
      "3008",
      "207",
      "206",
      "407",
      "2008",
      "308",
      "Partner",
      "5008",
      "208",
      "406"
   ],
   "Porsche":[
      "Macan",
      "911"
   ],
   "Ram":[
      "700",
      "Ram",
      "V700"
   ],
   "Renault":[
      "Symbol",
      "Stepway",
      "Fluence",
      "Sandero",
      "Logan",
      "Duster",
      "Kangoo",
      "Twingo",
      "Kwid",
      "Captur",
      "Megane",
      "Koleos",
      "Scenic",
      "Trafic",
      "Clio",
      "Oroch",
      "New",
      "R4",
      "Alaskan",
      "Scala"
   ],
   "Seat":[
      "Arona",
      "Altea",
      "Leon",
      "Ibiza",
      "Ateca"
   ],
   "Skoda":[
      "Yeti",
      "Rapid",
      "Fabia",
      "Superb"
   ],
   "Ssangyong":[
      "Actyon",
      "Korando",
      "Rexton",
      "Kyron",
      "Rodius"
   ],
   "Subaru":[
      "Legacy",
      "Forester",
      "Outback",
      "Xv",
      "Impreza",
      "Evoltis",
      "Tribeca"
   ],
   "Suzuki":[
      "Grand",
      "Vitara",
      "Swift",
      "Celerio",
      "Alto",
      "Jimny",
      "S-cross",
      "Baleno",
      "Ertiga",
      "Xl7",
      "Sj",
      "Ciaz",
      "Apv"
   ],
   "Toyota":[
      "Prado",
      "Fortuner",
      "Corolla",
      "Land",
      "Rav4",
      "4runner",
      "Tundra",
      "Hilux",
      "Tacoma",
      "Fj",
      "Yaris",
      "Estacas",
      "Burbuja",
      "Rush"
   ],
   "Volkswagen":[
      "Amarok",
      "Jetta",
      "Saveiro",
      "Polo",
      "Gol",
      "T-cross",
      "Bora",
      "Voyage",
      "Taos",
      "Fox",
      "Tiguan",
      "Virtus",
      "Escarabajo",
      "Passat",
      "Cross",
      "New",
      "Crossfox",
      "Transporter",
      "Nivus",
      "Golf",
      "Beetle",
      "Nuevo"
   ],
   "Volvo":[
      "Xc60",
      "S40",
      "S60",
      "Xc90",
      "V40",
      "Xc40",
      "C30"
   ],
   "Zhidou":[
      "D2s"
   ]
}


locations = {'Antioquia': ['Envigado', 'Medellín', 'Sabaneta', 'La Estrella', 'Bello', 'Girardota', 'Retiro', 'Itaguí', 'El Carmen de Viboral', 'Copacabana', 'Caldas', 'Abejorral', 'Rionegro'], 'Bogotá D.C.': ['Suba', 'Puente Aranda', 'Engativa', 'Bosa', 'Chapinero', 'Kennedy', 'Usaquén', 'Ciudad Bolívar', 'Teusaquillo', 'Rafael Uribe Uribe', 'Fontibón', 'Tunjuelito', 'Barrios Unidos', 'Antonio Nariño', 'Martires', 'Usme', 'San Cristobal Sur', 'Santa Fe'], 'Boyaca': ['Tunja', 'Duitama', 'Chiquinquirá'], 'Cundinamarca': ['Cota', 'La Calera', 'Facatativá', 'Soacha', 'Mosquera', 'Chía', 'Cajicá', 'Tabio', 'Cáqueza', 'Funza', 'Fusagasugá', 'Tenjo', 'Madrid', 'Zipaquirá', 'Sibaté'], 'Norte De Santander': ['Cúcuta'], 'Quindio': ['Armenia'], 'Santander': ['Floridablanca', 'Bucaramanga'], 'Valle Del Cauca': ['Cali']}